/* Run against a separately started preview: TEST_ORIGIN=http://127.0.0.1:... node scripts/check-todos.cjs */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');
const { expect } = require('@playwright/test');

const runtimePath = path.join(__dirname, '..', 'test-results', 'productivity-runtime.json');
const runtime = fs.existsSync(runtimePath) ? JSON.parse(fs.readFileSync(runtimePath, 'utf8').replace(/^\uFEFF/, '')) : {};
const origin = process.env.TEST_ORIGIN || runtime.origin || runtime.webOrigin;
if (!origin || new URL(origin).port === '3000') throw new Error('Set TEST_ORIGIN to an isolated preview; do not use the normal development session.');
const artifacts = path.join(__dirname, '..', 'test-results');
fs.mkdirSync(artifacts, { recursive: true });

(async () => {
  const browser = await chromium.launch({ headless: true });
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
    const page = await context.newPage();
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(`${origin}/todos`, { waitUntil: 'networkidle' });
    await page.getByRole('button', { name: /^新增待办/ }).waitFor();
    await page.waitForFunction(() => ![...document.querySelectorAll('button')].find(el => el.textContent.startsWith('新增待办'))?.disabled);
    await page.getByRole('button', { name: /^新增待办/ }).click();
    const dialog = page.getByRole('dialog');
    await dialog.locator('[name=title]').fill('Alpha 写完文章');
    await dialog.getByRole('textbox', { name: '任务详情 Markdown' }).fill('准备结构与示例。');
    await dialog.locator('[name=categoryId]').selectOption('work');
    await dialog.locator('[name=dueDate]').fill('2026-09-10');
    await dialog.locator('[name=urgent]').check();
    await dialog.getByRole('button', { name: '加入待办' }).click();
    await page.getByRole('region', { name: '重要 · 紧急', exact: true }).getByRole('button', { name: 'Alpha 写完文章', exact: true }).waitFor();
    await page.getByRole('button', { name: /^新增待办/ }).click();
    await dialog.locator('[name=title]').fill('Beta 阅读 20 页');
    await dialog.locator('[name=categoryId]').selectOption('study');
    await dialog.getByRole('button', { name: '加入待办' }).click();
    await page.getByRole('region', { name: '重要 · 不紧急', exact: true }).getByRole('button', { name: 'Beta 阅读 20 页', exact: true }).waitFor();

    if (!await page.getByRole('searchbox', { name: '搜索待办' }).isVisible()) await page.locator('summary').filter({ hasText: '整理我的待办' }).click();
    await page.getByRole('button', { name: '管理分类 +', exact: true }).click();
    await page.getByLabel('新分类', { exact: true }).fill('个人项目');
    await page.getByRole('radio', { name: '紫色', exact: true }).check();
    await page.getByRole('button', { name: '添加分类 +', exact: true }).click();
    const manager = page.getByRole('region', { name: '管理待办分类', exact: true });
    let categoryRow = manager.locator('div').filter({ has: page.locator('strong', { hasText: /^个人项目$/ }) }).last();
    await categoryRow.getByRole('button', { name: '改名 / 颜色', exact: true }).click();
    await page.getByLabel('分类名称', { exact: true }).fill('兴趣项目');
    await page.getByRole('button', { name: '保存分类 +', exact: true }).click();
    await page.getByRole('button', { name: '管理分类 −', exact: true }).click();
    await page.getByRole('button', { name: 'Alpha 写完文章', exact: true }).click();
    await dialog.locator('[name=categoryId]').selectOption({ label: '兴趣项目' });
    await dialog.getByRole('button', { name: '保存修改' }).click();
    const link = page.getByRole('link', { name: '◷ 开始专注', exact: true }).first();
    await expect(link).toHaveAttribute('href', /^\/pomodoro\?task=/);
    await page.getByRole('searchbox', { name: '搜索待办' }).fill('写完');
    await expect(page.getByRole('button', { name: 'Beta 阅读 20 页', exact: true })).toHaveCount(0);
    await page.getByRole('button', { name: '重置筛选 ×', exact: true }).click();
    await page.getByRole('button', { name: '列表', exact: true }).click();
    await page.getByLabel('排序', { exact: true }).selectOption('title');
    await expect(page.locator('article button[title="查看任务详情"]')).toHaveText(['Alpha 写完文章', 'Beta 阅读 20 页']);
    await page.getByLabel('分类', { exact: true }).selectOption('study');
    await expect(page.locator('article button[title="查看任务详情"]')).toHaveText(['Beta 阅读 20 页']);
    await page.getByLabel('分类', { exact: true }).selectOption('all');
    await page.getByLabel('轻重缓急', { exact: true }).selectOption('do');
    await expect(page.locator('article button[title="查看任务详情"]')).toHaveText(['Alpha 写完文章']);
    await page.getByLabel('轻重缓急', { exact: true }).selectOption('all');
    await page.getByLabel('截止日期', { exact: true }).selectOption('none');
    await expect(page.locator('article button[title="查看任务详情"]')).toHaveText(['Beta 阅读 20 页']);
    await page.getByLabel('截止日期', { exact: true }).selectOption('all');
    await page.getByRole('button', { name: '完成：Beta 阅读 20 页', exact: true }).click();
    await expect(page.getByRole('region', { name: '待办概览', exact: true })).toContainText(/50%/);
    await page.getByRole('button', { name: '统计', exact: true }).click();
    await expect(page.locator('[class*="weekChart"] header > strong')).toContainText(/1.*件完成/);
    await page.screenshot({ path: path.join(artifacts, 'todos-statistics-1440.png'), fullPage: true });
    await page.getByRole('button', { name: '列表', exact: true }).click();
    if (!await page.getByRole('searchbox', { name: '搜索待办' }).isVisible()) await page.locator('summary').filter({ hasText: '整理我的待办' }).click();
    await page.getByLabel('状态', { exact: true }).selectOption('done');
    await page.getByRole('button', { name: '重新打开：Beta 阅读 20 页', exact: true }).waitFor();
    await page.getByRole('button', { name: '重新打开：Beta 阅读 20 页', exact: true }).click();
    await page.getByLabel('状态', { exact: true }).selectOption('open');
    await page.getByRole('button', { name: '删除：Beta 阅读 20 页', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Beta 阅读 20 页', exact: true })).toHaveCount(0);
    await page.getByRole('button', { name: '撤销删除 ↶', exact: true }).click();
    await page.getByRole('button', { name: 'Beta 阅读 20 页', exact: true }).waitFor();
    if (!await page.getByRole('searchbox', { name: '搜索待办' }).isVisible()) await page.locator('summary').filter({ hasText: '整理我的待办' }).click();
    await page.getByRole('button', { name: '管理分类 +', exact: true }).click();
    await page.getByRole('button', { name: '删除分类：兴趣项目', exact: true }).click();
    await expect(page.locator('article').filter({ has: page.getByRole('button', { name: 'Alpha 写完文章', exact: true }) })).toContainText(/未分类/);
    await page.getByRole('button', { name: '撤销删除 ↶', exact: true }).click();
    await expect(page.locator('article').filter({ has: page.getByRole('button', { name: 'Alpha 写完文章', exact: true }) })).toContainText(/兴趣项目/);
    await page.getByRole('button', { name: '管理分类 −', exact: true }).click();
    await page.getByRole('button', { name: '统计', exact: true }).click();
    await page.getByLabel('统计月份', { exact: true }).fill('2026-09');
    await page.getByRole('heading', { name: '分类进度', exact: true }).waitFor();
    await page.getByRole('button', { name: '日历', exact: true }).click();
    await page.getByRole('button', { name: '2026-09-10，1 件待办', exact: true }).click();
    await page.getByRole('button', { name: 'Alpha 写完文章', exact: true }).waitFor();
    await page.screenshot({ path: path.join(artifacts, 'todos-calendar-1440.png'), fullPage: true });
    await page.getByRole('button', { name: '为这天添加 ＋', exact: true }).click();
    await expect(dialog.locator('[name=dueDate]')).toHaveValue('2026-09-10');
    await page.keyboard.press('Escape');
    const taskId = new URL(await page.getByRole('link', { name: '◷ 开始专注', exact: true }).first().getAttribute('href'), origin).searchParams.get('task');
    await page.goto(`${origin}/todos?task=${encodeURIComponent(taskId)}`, { waitUntil: 'networkidle' });
    await dialog.waitFor();
    await expect(dialog.locator('[name=title]')).toHaveValue('Alpha 写完文章');
    await page.keyboard.press('Escape');
    await page.goto(`${origin}/todos?task=does-not-exist`, { waitUntil: 'networkidle' });
    await page.getByRole('status').filter({ hasText: '这件待办已删除' }).waitFor();
    await expect(dialog).toBeHidden();
    await page.goto(`${origin}/todos`, { waitUntil: 'networkidle' });
    await page.reload({ waitUntil: 'networkidle' });
    await page.getByRole('button', { name: 'Alpha 写完文章', exact: true }).waitFor();
    await page.getByRole('button', { name: 'Beta 阅读 20 页', exact: true }).waitFor();
    for (const width of [1440, 390, 320]) {
      await page.setViewportSize({ width, height: 1000 });
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `horizontal overflow at ${width}`);
      await page.screenshot({ path: path.join(artifacts, `todos-${width}.png`), fullPage: true });
    }
    for (const view of ['列表', '日历', '统计']) {
      await page.getByRole('button', { name: view, exact: true }).click();
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `${view} overflow at 320`);
    }
    await page.getByRole('button', { name: '四象限', exact: true }).click();
    await page.getByRole('button', { name: /^新增待办/ }).click();
    const box = await dialog.boundingBox(); assert(box.x >= 0 && box.x + box.width <= 320);
    await page.screenshot({ path: path.join(artifacts, 'todos-editor-320.png'), fullPage: true });
    await page.keyboard.press('Escape');
    assert.deepEqual(errors, [], `Browser errors: ${errors.join('; ')}`);
    console.log('PASS Todo: task/category CRUD + undo, quadrant placement, search/sort/filter, completion/undo, calendar date add, statistics, Pomodoro link, reload persistence, Escape, mobile 320/390/1440.');
    await context.close();
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
