@Ottlog.Api_HostAddress = http://localhost:5229

GET {{Ottlog.Api_HostAddress}}/
Accept: application/json

###

GET {{Ottlog.Api_HostAddress}}/health

###

GET {{Ottlog.Api_HostAddress}}/openapi/v1.json
Accept: application/json

###

GET {{Ottlog.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
