// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ottlog.Api.Data;

#nullable disable

namespace Ottlog.Api.Migrations
{
    [DbContext(typeof(BlogDb))]
    partial class BlogDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Ottlog.Api.Data.Administrator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailedLogins")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LockedUntil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("Ottlog.Api.Data.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoCover")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Published")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PublishedMini")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("Ottlog.Api.Data.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Approved")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Ottlog.Api.Data.Favorite", b =>
                {
                    b.Property<string>("Owner")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Owner", "ArticleId");

                    b.HasIndex("ArticleId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("Ottlog.Api.Data.PersonalToolState", b =>
                {
                    b.Property<string>("Owner")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Owner", "Key");

                    b.ToTable("PersonalToolStates");
                });

            modelBuilder.Entity("Ottlog.Api.Data.Reader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLogins")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LockedUntil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Readers");
                });

            modelBuilder.Entity("Ottlog.Api.Data.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Ottlog.Api.Data.WeChatBinding", b =>
                {
                    b.Property<string>("Owner")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Owner");

                    b.HasIndex("AppId", "OpenId")
                        .IsUnique();

                    b.ToTable("WeChatBindings");
                });

            modelBuilder.Entity("Ottlog.Api.Data.WeChatPomodoroReminder", b =>
                {
                    b.Property<string>("Owner")
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Event")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RemindAtEpoch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Revision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SourceDeadline")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtEpoch")
                        .HasColumnType("INTEGER");

                    b.HasKey("Owner", "RunId", "Event");

                    b.HasIndex("Status", "RemindAtEpoch");

                    b.ToTable("WeChatPomodoroReminders");
                });

            modelBuilder.Entity("Ottlog.Api.Data.WeChatReminder", b =>
                {
                    b.Property<string>("Owner")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RemindAtEpoch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Revision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtEpoch")
                        .HasColumnType("INTEGER");

                    b.HasKey("Owner", "TaskId");

                    b.HasIndex("Status", "RemindAtEpoch");

                    b.ToTable("WeChatReminders");
                });

            modelBuilder.Entity("Ottlog.Api.Data.Comment", b =>
                {
                    b.HasOne("Ottlog.Api.Data.Article", null)
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ottlog.Api.Data.Favorite", b =>
                {
                    b.HasOne("Ottlog.Api.Data.Article", null)
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
